language: 
  - python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda init bash
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda

install:
  # NOTE : conda-forge removed the .pc files for blas, cblas, lapack, and
  # lapacke inadvertently. Setting lapack < 3.9.0 ensures the .pc files are
  # available. See this issue:
  # https://github.com/conda-forge/blas-feedstock/issues/58
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION "lapack<3.9.0" numpy cython ipopt future six setuptools sphinx numpydoc pkg-config
  - conda activate test-env

before_script:
  - conda info -a
  - conda list
  - pip --version
  - pip freeze

script:
  # Make sure the library installs.
  - python setup.py install
  - python -c "import cyipopt"
  # Run the Pytest tests.
  - conda install pytest
  - pytest
  # Make sure the Sphinx docs build.
  - cd docs && make clean && make html && cd ..
