name: tests

on:
  push:
    branches: master
  pull_request:
    branches: master

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        ipopt-version: ['3.12', '3.13', '3.14']
        exclude:
          - os: windows-latest
            ipopt-version: '3.12'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout CyIpopt
        uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install basic dependencies
        run: |
          conda install -n base libarchive
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda install -q -y lapack "libblas=*=*netlib" cython>=0.26 "ipopt=${{ matrix.ipopt-version }}" numpy>=1.15 pkg-config>=0.29.2 setuptools>=39.0
      - name: Install CyIpopt
        run: |
          rm pyproject.toml
          python -m pip install .
          conda list
      - name: Test with pytest
        run: |
          python -c "import cyipopt"
          conda remove lapack
          conda install -q -y cython>=0.26 "ipopt=${{ matrix.ipopt-version }}" numpy>=1.15 pkg-config>=0.29.2 setuptools>=39.0 pytest>=3.3.2
          conda list
          pytest
      - name: Test with pytest and scipy, new ipopt
        # cyipopt can build with these dependencies, but it seems impossible to
        # also install scipy into these environments likely due to SciPy and
        # Ipopt needed different libfortrans.
        if: (matrix.ipopt-version != '3.12' && matrix.python-version != '3.11') || (matrix.ipopt-version != '3.12' && matrix.python-version != '3.10' && matrix.os != 'macos-latest')
        run: |
          conda install -q -y -c conda-forge cython>=0.26 "ipopt=${{ matrix.ipopt-version }}" numpy>=1.15 pkg-config>=0.29.2 setuptools>=39.0 pytest>=3.3.2 scipy>=0.19.0
          conda list
          pytest
