name: test

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        ipopt-version: [3.12, 3.13]
        exclude:
          - os: windows-latest
            ipopt-version: 3.12
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Pycollo
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-build-version: 3.21.4
      - name: Install basic dependencies
        run: conda install -q -y lapack "libblas=*=*netlib" cython>=0.26 "ipopt=${{ matrix.ipopt-version }}" numpy>=1.15 pkg-config>=0.29.2 setuptools>=39.0
      - name: Install CyIpopt
        run: python setup.py install
      - name: Test with pytest
        run: 
          python -c "import cyipopt"
          conda install -y -q pytest>=3.3.2
          pytest
          conda install -y -q scipy>=0.19.1
          pytest
      - name: Test building documentation
        run: |
          conda install -y -q --file docs/requirements.txt
          cd docs && make clean && make html && cd ..
